[build]
     command = "npm run build"
     publish = ".next"

   [[plugins]]
     package = "@netlify/plugin-nextjs"
     
    [output]
     dir = ".next"

     [
build
]
  base = "denunciaapp"
[
build
]
  command = "npm run build"
  publish = "/PROJETO3/denunciaapp/.next"